 language: java
 
 jdk:
   - oraclejdk8
 
 os:
   - linux
 
 branches:
   only:
     - master

 cache:
   directories:
   - $HOME/.gradle

 before_script:
   - git fetch
   - git checkout -b gh-pages
   - git merge origin/master
   - git rm --cached --ignore-unmatch index.html

 script:
   - ./gradle build
   - ./gradle test

 after_script:
   - git add .
   # something@example.com
   - git config user.email "${GIT_EMAIL}"
   # First Last
   - git config user.name "${GIT_NAME}"
   - git commit -m "updating outputs"
   # https://${GH_TOKEN}@github.com/asciidoctor/asciidoctor-gradle-examples.git
   - git push -f "${GIT_URL}" gh-pages > /dev/null 2>&1
 before_cache:
   - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
   - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
 cache:
   directories:
     - $HOME/.gradle/caches/
     - $HOME/.gradle/wrapper/
